apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: masters
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::506977970728:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-14T21:27:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-14T21:27:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1675"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c78cf6f4-ee54-4599-a461-c3f74905e168
